### ISSUE TITLE
Cannot get all inventory

### ISSUE THREAD

**Issue by aaijtm** [NCRCounterpointAPI/APIGuide#23]
The inventory call executes to work but returns the following error:
The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Too many parameters were provided in this RPC request. The maximum is 2100.
The general introduction to the api implies that pagination is possible on some of the api calls but there is nothing I can find in the rest of the documentation to indicate what that syntax would look like, or to indicate if the api call for "get inventory by location" supports pagination.  Can you please point us in the right direction.

**Comment by BrianRoyal** [comment]
We are having this issue as well.  We cannot get all items, because we exceed the maximum parameters.  The only apparent limiters are category or subcategory.  Can we get a shorter list?  Is pagination available?  And specifically, can we pull up items based on Ecommerce status or last modified date?  

Thanks in advance!

**Comment by BrianRoyal** [comment]
NCR - I now see your comments on issue #7 that this is a known issue, due to be fixed with the next patch or release.  Any info you have about timing on that release would be very much appreciated.  Thank you!

**Comment by MikeRitchie** [comment]
API 1.1 release is scheduled for late August. More details to be posted soon.
