### ISSUE TITLE
How to create Order in counterpoint Company using CounterPoint API

### ISSUE THREAD

**Issue by amitcorcrm** [NCRCounterpointAPI/APIGuide#24]
Hello Mike,
I want to push my eCommerce orders into Counterpoint Company using the counterpoint API, I have go through all the company endpoint API and I did not found any API for creating a new order. 
If it is possible so please provide guidance on this how can i achieve it. 
Please provide a link where I can get help to create new Order and create new Items using API.

Thanks In advanced!

Regards 
Amit

**Comment by jameslaurenti** [comment]
Just wanted to piggyback of this ticket to say I'm looking into the same thing. :)

I believe this is the endpoint:
https://github.com/NCRCounterpointAPI/APIGuide/blob/master/Endpoints/POST_Document.md

I don't quite understand how to define the document type as an order though.  Similarly, was wondering if there's some additional documentation that's out there on field definitions, and what is required when specifically submitting a pre-processed eCommerce order (i.e. payment has already been captured) to Counterpoint so that inventory/sales can be consolidated?

**Comment by MikeRitchie** [comment]
The first example on the POST Document page shows how an order is submitted:
https://github.com/NCRCounterpointAPI/APIGuide/blob/master/Endpoints/POST_Document.md

The key fields are:
DOC_TYP = O (for order)
TKT_TYP = T (ticket)

and each line should also have
LIN_TYP = O

**Comment by MikeRitchie** [comment]
Also, when payment has already been captured, you would want to submit a PS_DOC_PMT record for a cash pay type, and FINAL_PMT should be "N". Any credit card information submitted in PS_DOC_PMT would be processed either immediately or when the order released, so if payment was already captured by the eComm site credit card payment types shouldn't be submitted.

**Comment by MikeRitchie** [comment]
Is anything additional needed on this thread? If so can you refresh what you need help with, or confirm it's OK to close the issue?

**Comment by jameslaurenti** [comment]
@MikeRitchie -- thanks for the feedback.  I'm not sure about Amit, but on my end, our production team temporarily changed gears and is finalizing a different project. I'm looking to pick this up again though afterwards.  

From my standpoint it's okay if you want to close this as I have the direct link still to the issue URL, and I can refer to it later on.

At worst, if we do run into problems as we pick things up again, I'll re-open.  Thanks for the help!

**Comment by MikeRitchie** [comment]
Thank you. I'll close this, and you can always open a new issue if needed.
