### ISSUE TITLE
API not compatible...

### ISSUE THREAD

**Issue by osain86** [NCRCounterpointAPI/APIGuide#28]
We updated our systems with the new Service Pack (8.5.3) from NCR, now the API is not working.
Authentication is broken, it's not possible to add company admins.
API Error: "Database version 32.12 is not supported for ICompanyAdminBusiness"

Please, let me know what to do. Thanks!

**Comment by MikeRitchie** [comment]
The API 1.0 release does not currently work with Counterpoint 8.5.3. We have started development on an API 1.1 release that will include 8.5.3 support. We should have a target date for that release shortly.

**Comment by blueoceanyyc** [comment]
Can you confirm as of today if the API supports version 8.5.3 yet? I am having the same error as above when trying to add/manage the company admins from the API management website. Thanks
https://www.screencast.com/t/kS8LAmy5AX

I am also receiving this error message when making any api call, which I think is related not having a company admin setup? 

[ResponseStatus] => stdClass Object
        (
            [ErrorCode] => Exception
            [Message] => Error trying to resolve Service 'CPAPI.Common.IUserRoleBusiness' or one of its autowired dependencies (see inner exception for details).
            [StackTrace] =>    at Funq.Container.ResolveImpl[TService,TArg](String name, Boolean throwIfMissing, TArg arg)
   at CPAPI.Common.RoleAttribute.Execute(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.RequestFilterAttribute.RequestFilter(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.Host.RestHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)
        )


Please advise. Thanks for your help

**Comment by MikeRitchie** [comment]
Correct. The 2.0 API, released Friday, is compatible with Counterpoint 8.5.3 and will address the error with Database version 32.12 in your screenshot. You can get the 2.0 API via ftp from the same location your downloaded the 1.0 API.

The other error is likley due to not having proper permissions for the user making the API call. A company admin needs to create a role and assign it to a user in order to allow that user to make specific API calls:
https://github.com/NCRCounterpointAPI/APIGuide/blob/master/InstallationAndConfiguration/Configuring.md
