### ISSUE TITLE
Cache or api update problems

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#32]
When making changes to items like EC categories for example, the changes are not reflected in api call until either a deleted cached is sent or the api service is restarted.

**Comment by MikeRitchie** [comment]
Configuration data that isn't expected to change frequently is cached by the API, in order to reduce hits on the database server and help with performance.  Values are cached for 24 hours. 

To force the cache to be invalidated, you can include the header ServerCache:no-cache in your request.

Currently, caching is not configurable, but it's certainly something we'll consider in the future.
