### ISSUE TITLE
Not being able to create a role

### ISSUE THREAD

**Issue by Nepherhotep** [NCRCounterpointAPI/APIGuide#6]
When I try to create a role according to this guide https://github.com/NCRCounterpointAPI/APIGuide/blob/master/InstallationAndConfiguration/Configuring.md#creating-and-assigning-roles, I get error "Unable to retrieve endpoint data: undefined". As result I can't select endpoints which should be accessible for the given user.

![failed-to-add-role](https://cloud.githubusercontent.com/assets/2122618/23362832/ade1a58c-fd08-11e6-8133-803ba043f903.png)

**Comment by MikeRitchie** [comment]
Could you please recreate the issue, then post your most recent log file from C:\Program Files (x86)\NCR\Counterpoint API\Logfiles?

Thank you

**Comment by Nepherhotep** [comment]
[5126e1-logfiles.zip](https://github.com/NCRCounterpointAPI/APIGuide/files/803850/5126e1-logfiles.zip)

**Comment by Nepherhotep** [comment]
@MikeRitchie emailed separately

**Comment by MikeRitchie** [comment]
We're still researching this. Could you tell us what OS the server and browser are running on (and if they're the same machine?) Also, it looks like you are using IE. If possible, could you try Chrome to see if the behavior is any different?

**Comment by Nepherhotep** [comment]
I used Firefox, when I tried Chrome, it worked fine! Thanks, I believe you can close the issue if you don't intent to support Firefox.

**Comment by MikeRitchie** [comment]
Thanks for the quick feedback. I'll close this, but we'll have an internal task around browser support, which we haven't been clear enough on. Glad you're up & running though!

**Comment by tjohnson-github** [comment]
I just wanted to put some other information in here to maybe help someone else because this solution is little miss leading in the since that I'm not sure it had to do with the specific browser. I ran into this twice and both times was because I did not first add Company admins under companies. Once you choose the correct users that you will be logging in as to edit roles, you will get this error. At least in both cases I forgot to do this first. Hope that may help someone.
