### ISSUE TITLE
Handler for Request not found (404)

### ISSUE THREAD

**Issue by drewlsvern** [NCRCounterpointAPI/APIGuide#93]
I seem to be receiving the following error seen below, when trying to update an existing customer.
I looked at the docs and don't seem to be missing anything.
Please advise.

Handler for Request not found (404):

  Request.HttpMethod: PUT
  Request.PathInfo: /Customer/HR-123456
  Request.QueryString: 
  Request.RawUrl: /Customer/HR-123456

**Comment by MikeRitchie** [comment]
It looks like the error is because you are attempting a PUT rather than a PATCH. Currently, we only support PATCH for updating a customer. PATCH indicates a partial update, which means you're only updating the fields provided in the body, and other data fields for the customer remain as is. PUT typically is a full update, meaning you're replacing the entire customer record with the data included in the body of the request (not the case here).

I did note in testing this that it appears the endpoint will incorrectly return a SUCCESS result when an invalid CUST_NO is provided in the URL, so please be aware of that. I'll submit that for correction.

**Comment by drewlsvern** [comment]
I understand the different HTTP verbs, but I was attempting a PUT as that is what the documentation states. In fact, I don't see any endpoints that suggest a PATCH according to the documentation.

Anyhow using a PATCH does work, thanks.

**Comment by MikeRitchie** [comment]
I see the issue. The list of endpoints shows it as a PATCH, but the page it links to incorrectly says PUT. I've corrected the page.

**Comment by drewlsvern** [comment]
I see you update the [page ](https://github.com/NCRCounterpointAPI/APIGuide/blob/master/Endpoints/PUT_Customer.md) to specifiy PATCH, but I see don't see any files that actually suggest a patch.

![capture](https://user-images.githubusercontent.com/6773010/35451004-74738236-0287-11e8-9b1f-873f46b8a0aa.PNG)

**Comment by MikeRitchie** [comment]
OK. The filename is incorrect as well. We will update.
